name: Checkov Analysis

on:
  push:
    paths:
      - '101-vm-with-infrastructure/**'

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d 101-vm-with-infrastructure

